### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by azekillDIABLO** [qub3d/qub3d#8]
Sorry to open an issue for nothing 😑. But I didn't find any way to contact people in the project! I originally sent a message to the Minecore mail, but I didnt realised the project was dead. Just to say, if you need some guy to help I'll Always be here. My project is extremely close to yours! [Some link to it because advertizing a project is fun.](https://github.com/azekillDIABLO/omicron) Please pass by and tell me if you need something or have some idea!

Cheers!
PS: toby, your texturing skill are amazing! :O 
EDIT: I managed to miss the link to website sorry.

**Comment by tobyplowy** [comment]
@azekillDIABLO Oh hi, long time no see.
I have to close this issue but I definitely want to keep in contact with you.
Check out our discord server https://discord.gg/ahR2jZ

**Comment by azekillDIABLO** [comment]
yep a long time :')

sorry for the whole mess! will try to find back my discord account!

**Comment by TMcSquared** [comment]
Heya @azekillDIABLO it's me ThomasMonroe/Tre'/TMcSquared xD long time no see!

**Comment by azekillDIABLO** [comment]
@TMcSquared Wait really? LOL this world is small

**Comment by TMcSquared** [comment]
@azekillDIABLO yep, it's me. 😛
